name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Select the repository from ./models'
        required: true
        default: ''
      image_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Validate and normalize repo_name input
        id: validate_repo
        run: |
          if [ -z "${{ github.event.inputs.repo_name }}" ]; then
            echo "Repository name input is required."
            exit 1
          fi
          
          # Convert the repo_name to lowercase
          NORMALIZED_REPO_NAME=$(echo "${{ github.event.inputs.repo_name }}" | tr '[:upper:]' '[:lower:]')
          
          MODEL_DIR="./models/${{ github.event.inputs.repo_name }}"
          if [ ! -d "$MODEL_DIR" ]; then
            echo "The specified repository does not exist: $MODEL_DIR"
            exit 1
          fi
          
          echo "MODEL_DIR=$MODEL_DIR" >> $GITHUB_ENV
          echo "NORMALIZED_REPO_NAME=$NORMALIZED_REPO_NAME" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.NORMALIZED_REPO_NAME }}:${{ github.event.inputs.image_tag }} -f ${{ env.MODEL_DIR }}/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.NORMALIZED_REPO_NAME }}:${{ github.event.inputs.image_tag }}
